# Generated by Django 3.2.9 on 2021-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgc_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
