# Generated by Django 3.2.9 on 2021-12-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgc_app', '0004_rename_boardgame_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Details',
        ),
    ]
