# Generated by Django 3.2.9 on 2021-12-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgc_app', '0007_auto_20211212_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='currentowner',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
