# Generated by Django 3.2.9 on 2021-12-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bgc_app', '0007_auto_20211212_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='currentlowner',
            new_name='currentowner',
        ),
    ]
